# _config.yml 文件内容

# 网站基本信息
title: 软件工程作业存档
description: 课程学习

# 核心：指定主题名称 (例如使用 GitHub Pages 支持的 Cayman 主题)
theme: jekyll-theme-cayman 

# 可选：设置文章的默认 URL 结构，以实现 /posts/ 路径
# 如果您使用下面的 permalink 结构，那么文章的 permalink 字段可以更简洁。
permalink: /:categories/:title/
